name: Hello World Workflow

# This workflow is manually triggered using the 'workflow_dispatch' event
on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Say Hello
        run: echo "Hello $USER, World!"

      - name: Show OS
        run: echo "$RUNNER_OS"

      - name: ping registry
        run: ping -c 4 registry.cp.its.uu.nl
